# - id: 'livingroom_button_bedside_wife_turn_off_all'
#   alias: Выключить все
#   trigger:    
#     event_type: click
#     platform: event
#     event_data:
#       entity_id: binary_sensor.livingroom_button_bedside_wife
#       click_type: long_click_press
#   action:
#     service: switch.turn_off
#     entity_id:
#       - switch.kitchen_left_switch_ceiling_light
#       - switch.kitchen_right_switch_backlight
#       - switch.restroom_switch_ceiling_light
#       - switch.bathroom_switch_right_ceiling_light
#       - switch.bathroom_switch_left_additional_light
#       - switch.livingroom_switch_ceiling_light
#       - switch.hall_switch_right_ceiling_light
#       - switch.playroom_switch_ceiling_light
# - id: 'livingroom_button_bedside_wife_voice_activate'
#   alias: Активация голосового ассистента
#   trigger:    
#     event_type: click
#     platform: event
#     event_data:
#       entity_id: binary_sensor.livingroom_button_bedside_wife
#       click_type: single
#   action:
#     service: voice_commands.activate
